services:
  zed-camera:
    container_name: zed_jetson_camera_2
    build: .
    runtime: nvidia
    privileged: true  # Give the container full access to host devices
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_XCB_GL_INTEGRATION=xcb_egl
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # For X11 forwarding
      - .:/app
    ports:
      - 9000:9000
    devices:
      - /dev:/dev
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/ttyACM2:/dev/ttyACM2
      - /dev/ttyACM3:/dev/ttyACM3
      - /dev/video0:/dev/video0
      - /dev/bus/usb:/dev/bus/usb  # Allow USB access
    network_mode: host  # Use host network
    stdin_open: true  # Keep the container open (interactive)
    tty: true  # Allocate a pseudo-TTY to keep it running
