footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
footprint_padding: 0.01

robot_radius: 0.25
inflation_radius: 0.55
obstacle_range: 2.5
raytrace_range: 3.0

# Update rate untuk global dan local costmaps
observation_sources: scan
scan: {sensor_frame: scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
