global_costmap:
  global_frame: "map"
  robot_base_frame: "base_footprint"
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  static_map: true

  plugins:
    - {name: "static_layer", type: "costmap_2d::StaticLayer"}
    - {name: "obstacle_layer", type: "costmap_2d::ObstacleLayer"}
    - {name: "inflation_layer", type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: "scan"
  scan: {data_type: "sensor_msgs/LaserScan", topic: "scan", marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.55
  cost_scaling_factor: 10.0

