global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true

  transform_tolerance: 0.5

  inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0
    inflation_radius: 0.55

  obstacle_layer:
    enabled: true
    max_obstacle_height: 2.0
    obstacle_range: 2.5
    raytrace_range: 3.0
    observation_sources: scan
    scan: {sensor_frame: scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
