# move_base_params.yaml

# Define the base local planner
base_local_planner: dwa_local_planner/DWAPlannerROS

# Costmap parameters (example configuration)
global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 0.0
      static_map: true
      transform_tolerance: 0.5
      footprint: [[-0.2, -0.2], [0.2, -0.2], [0.2, 0.2], [-0.2, 0.2]]
      resolution: 0.05
      width: 10
      height: 10
      origin_x: -5.0
      origin_y: -5.0

local_costmap:
  local_costmap:
    ros__parameters:
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 0.0
      static_map: false
      transform_tolerance: 0.5
      footprint: [[-0.2, -0.2], [0.2, -0.2], [0.2, 0.2], [-0.2, 0.2]]
      resolution: 0.05
      width: 5
      height: 5
      origin_x: -2.5
      origin_y: -2.5

